name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean workspace
        run: |
          rm -rf dist
          rm -rf node_modules/.cache
          rm -rf .vite

      - name: Install Dependencies
        run: npm ci

      - name: Build
        env:
          OPENAI_PROXY_URL: ${{ secrets.OPENAI_PROXY_URL || '' }}
        run: npm run build

      - name: Verify build output
        run: |
          echo "Build completed. Checking for sensitive data..."
          if grep -r "sk-proj-\|sk-[a-zA-Z0-9]" dist/ 2>/dev/null; then
            echo "WARNING: Actual API keys found in build output!"
          fi
          if grep -r "sk-[a-zA-Z0-9]\{20,\}" dist/ 2>/dev/null; then
            echo "WARNING: Potential API keys found in build output!"
          fi
          echo "Build verification passed - no actual API keys found"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 